name:                vformat
version:             0.14.1.0
synopsis:            A Python str.format() like formatter
description:         Please see the http://hackage.haskell.org/package/vformat
github:              versioncloud/vformat
category:            Text, Format
license:             BSD3
maintainer:          Jorah Gao <jorah@version.cloud>
copyright:           (c) 2019 Version Cloud

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.9 && < 5
- containers >= 0.5.9 && < 1.0
- exceptions >= 0.8 && < 1.0
- template-haskell >= 2.7 && < 3.0

library:
  source-dirs: src
  exposed-modules:
    - Text.Format
    - Text.Format.TH

tests:
  vformat-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vformat
    - hspec >= 2.1 && < 3.0
    - QuickCheck >= 2.0 && < 3.0
